name: abcd
batch_size: 16
test_batch_size: 16
val_batch_size: 16
train_set: 0.7
val_set: 0.1
node_feature: /local/home/xkan/ABCD/ABCD/abcd_rest-pearson-HCP2016.npy
time_seires: /local/home/xkan/ABCD/ABCD/abcd_rest-timeseires-HCP2016.npy
node_id: /local/home/xkan/ABCD/ABCD/ids_HCP2016.txt
seires_id: /local/home/xkan/ABCD/ABCD/ids_HCP2016_timeseires.txt
label: /local/home/xkan/ABCD/ABCD/id2sex.txt
drop_last: True
stratified: False
regression: False
column: sex