name: abcd
batch_size: 16
test_batch_size: 16
val_batch_size: 16
train_set: 0.7
val_set: 0.1
node_feature: /home/achengu/ABCD/abcd_rest-pearson-HCP2016-1024.npy
time_seires: /home/achengu/ABCD/abcd_rest-timeseires-HCP2016-1024.npy
node_id: /home/achengu/ABCD/ids_HCP2016_timeseires-1024.txt
seires_id: /home/achengu/ABCD/ids_HCP2016_timeseires-1024.txt
label: /home/achengu/ABCD/id2sex.txt
drop_last: True
stratified: False
regression: False
column: sex