name: abcd
batch_size: 16
test_batch_size: 16
val_batch_size: 16
train_set: 0.7
val_set: 0.1
node_feature: /home/achengu/ABCD/abcd_rest-pearson-HCP2016-1024.npy
time_seires: /home/achengu/ABCD/abcd_rest-timeseires-HCP2016-1024.npy
node_id: /home/achengu/ABCD/ids_HCP2016_timeseires-1024.txt
seires_id: /home/achengu/ABCD/ids_HCP2016_timeseires-1024.txt
label: /home/achengu/ABCD/abcd_tbss01_baseline.csv
drop_last: True
stratified: False
regression: True

# "nihtbx_picvocab_uncorrected",
# "nihtbx_picvocab_agecorrected",
# "nihtbx_cryst_uncorrected",
# "nihtbx_cryst_agecorrected",
# "nihtbx_reading_agecorrected",
# "nihtbx_totalcomp_uncorrected",
# "nihtbx_totalcomp_agecorrected",
column: nihtbx_totalcomp_uncorrected
timeseries_sz: 1024