name: abcd
batch_size: 16
test_batch_size: 16
val_batch_size: 16
train_set: 0.7
val_set: 0.1
node_feature: /local/home/xkan/ABCD/ABCD/abcd_rest-pearson-HCP2016.npy
time_seires: /local/home/xkan/ABCD/ABCD/abcd_rest-timeseires-HCP2016.npy
node_id: /local/home/xkan/ABCD/ABCD/ids_HCP2016.txt
seires_id: /local/home/xkan/ABCD/ABCD/ids_HCP2016_timeseires.txt
label: /local/home/xkan/ABCD/ABCD/abcd_tbss01_baseline.csv
drop_last: True
stratified: False
regression: True

# "nihtbx_picvocab_uncorrected",
# "nihtbx_picvocab_agecorrected",
# "nihtbx_cryst_uncorrected",
# "nihtbx_cryst_agecorrected",
# "nihtbx_reading_agecorrected",
# "nihtbx_totalcomp_uncorrected",
# "nihtbx_totalcomp_agecorrected",
column: nihtbx_totalcomp_uncorrected
timeseries_sz: 1024