name: pnc
batch_size: 16
test_batch_size: 16
val_batch_size: 16
train_set: 0.7
val_set: 0.1
node_feature: /home/achengu/PNC_data/514_pearson.npy
time_seires: /home/achengu/PNC_data/514_timeseries.npy
label: /home/achengu/PNC_data/PNC_Gender_Age.csv
drop_last: True
stratified: False
regression: False
